baseurl: "/lod-berlin-einwohner" # the subpath of your site, e.g. /blog
url: "https://berlinonline.github.io" # the base hostname & protocol for your site, e.g. http://example.com
true_url: "https://berlinonline.github.io" # This duplication is necessary to make relative links work when
    # running the Jekyll-Site locally, when `url` is replaced with somehting like http://localhost:4000

dataset_url: "/lod-berlin-einwohner/"
dataset_breadcrumb: "Datensatz"
cbd_folder: "cbds/"

exclude:
    - bin/
    - data/
    - conf/
    - README.md
    - TODO.md
    - Makefile
    - Gemfile
    - requirements.txt
    - csv_schema.csv
    - query/
    - venv/
plugins:
    - jekyll-rdf

# Jekyll RDF settings
jekyll_rdf:
    path: "$SOURCE_PATH"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?predicate ?object FILTER(STRSTARTS(STR(?resourceUri), 'https://berlinonline.github.io/lod-berlin-einwohner')) }"
    default_template: "default"
    class_template_mappings:
        "http://rdfs.org/ns/void#Dataset": "dataset"
        "https://schema.org/Organization": "organization"
        "https://berlinonline.github.io/lod-sg/ImprintPage": "imprint"
        "https://cube.link/Cube": "cube"
        "https://cube.link/Observation": "observation"
        "https://cube.link/ObservationSet": "observation_set"
        "http://www.w3.org/2002/07/owl#Ontology": "voc_ontology"
        "http://www.w3.org/2002/07/owl#Class": "voc_class"
        "http://www.w3.org/2000/01/rdf-schema#Class": "voc_class"
        "http://www.w3.org/2002/07/owl#DatatypeProperty": "voc_property"
        "http://www.w3.org/2002/07/owl#ObjectProperty": "voc_property"
        "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property": "voc_property"
        "https://berlinonline.github.io/lod-berlin-einwohner/vocab/city_region": "voc_other"
